server:
  port: 8091

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus


enableSwagger: ${ENABLE_SWAGGER:true}

role-assignment-service:
  url: ${ROLE_ASSIGNMENT_URL:http://role-assignment}

camunda:
  url: ${CAMUNDA_URL:http://camunda-bpm/engine-rest}

ccd:
  url: ${CCD_URL:http://ccd-data-store-api}
core_case_data:
  api:
    url: ${CCD_URL:http://ccd-data-store-api}

auth:
  provider:
    service:
      client:
        baseUrl: ${S2S_URL:http://service-auth-provider-api}

idam:
  baseUrl: ${IDAM_URL:http://sidam-api}
  redirectUrl: ${IA_IDAM_REDIRECT_URI:http://localhost:3002/oauth2/callback}
  s2s-auth:
    url: ${S2S_URL:http://service-auth-provider-api}
    secret: ${S2S_SECRET_TASK_CONFIGURATION_API:AAAAAAAAAAAAAAAC}
    name: wa_task_configuration_api
  system:
    username: ${TEST_LAW_FIRM_A_USERNAME:some_user@hmcts.net}
    password: ${TEST_LAW_FIRM_A_PASSWORD:password}
    scope: "openid profile roles"

spring:
  application:
    name: WA Task Configuration
  main:
    allow-bean-definition-overriding: true
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      indent_output: true

  security:
    oauth2:
      client:
        registration:
          oidc:
            client-id: ${WA_IDAM_CLIENT_ID:wa}
            client-secret: ${WA_IDAM_CLIENT_SECRET:something}
