server:
  port: 8091

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

config:
  stacktraceEnabled:  ${STACKTRACE_ENABLED:false}


enableSwagger: ${ENABLE_SWAGGER:true}

camunda:
  url: ${CAMUNDA_URL:http://localhost:8080/engine-rest}

ccd:
  url: ${CCD_URL:http://ccd-data-store-api}
core_case_data:
  api:
    url: ${CCD_URL:http://ccd-data-store-api}

auth:
  provider:
    service:
      client:
        baseUrl: ${S2S_URL:http://service-auth-provider-api}

idam:
  baseUrl: ${IDAM_URL:http://sidam-api}
  redirectUrl: ${IA_IDAM_REDIRECT_URI:http://localhost:3002/oauth2/callback}
  s2s-auth:
    url: ${S2S_URL:http://service-auth-provider-api}
    secret:
      camunda: ${S2S_SECRET_TASK_CONFIGURATION_API:AAAAAAAAAAAAAAAC}
      ccd: AAAAAAAAAAAAAAAC
    name:
      camunda: ${S2S_NAME_TASK_CONFIGURATION_API:wa_task_configuration_api}
      ccd: iac
  system:
    username: ${TEST_LAW_FIRM_A_USERNAME:some_user@hmcts.net}
    password: ${TEST_LAW_FIRM_A_PASSWORD:password}
    scope: "openid profile roles"

#If you use a database then uncomment below lines and update db properties accordingly

spring:
  application:
    name: WA Task Configuration
  main:
    allow-bean-definition-overriding: true
  jackson:
    property-naming-strategy: SNAKE_CASE

  security:
    oauth2:
      client:
        registration:
          oidc:
            client-id: ${IA_IDAM_CLIENT_ID:iac}
            client-secret: ${IA_IDAM_SECRET:something}
